apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv

spec:
  capacity:
    storage: 5Gi

  volumeMode: Filesystem

  accessModes:
    - ReadWriteMany

  persistentVolumeReclaimPolicy: Retain

  storageClassName: efs-sc

  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-00bd326dbc8e3525b 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
  namespace: student-app

spec:
  accessModes:
    - ReadWriteMany

  storageClassName: efs-sc

  resources:
    requests:
      storage: 5Gi
