apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: student-app

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: cmVkaGF0MTIz
  MYSQL_DATABASE: c3R1ZGVudF9kYg==
  MYSQL_USER: YWRtaW4=
  MYSQL_PASSWORD: cmVkaGF0MTIz
